before_install:
  rvm install 2.2.2
language: ruby
rvm:
- 2.2.2
bundler_args: --without production
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- CODECLIMATE_REPO_TOKEN=e47363a705f45d6d9fcb8ac01305cbe571b03af4268d94a3cf8b08d58f49ec71 bundle exec rake
addons:
  code_climate:
    repo_token: e47363a705f45d6d9fcb8ac01305cbe571b03af4268d94a3cf8b08d58f49ec71
notifications:
  slack: cs169-team:jPDjlLQAetDDxFKhc61J72zd