before_install:
  rvm install 2.2.2
language: ruby
rvm:
- 2.2.2
bundler_args: --without production
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- CODECLIMATE_REPO_TOKEN=2b9c549b8f94c0e42f6161f7577038885aa7b21f4a38fc8525a828a96abd6769 bundle exec rake
addons:
  code_climate:
    repo_token: 2b9c549b8f94c0e42f6161f7577038885aa7b21f4a38fc8525a828a96abd6769
notifications:
  slack: cs169-team:efQmw1c7Yvi5Zp1slBG9IkTg